### ISSUE TITLE
Make the data part in LevelCacheStore optional

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/merkletree#52]
We need a version of the `LevelCacheStore` that only caches the merkle tree part, and relies on callback, to retrieve data needed to rebuild the tree. 

The callback should look sth like `Fn(start: usize, end: usize, buf: &mut [u8]) -> Result<()>`, such that it can be called instead of `store_read_into` when the `LevelCacheStore` needs to access this data.

**Comment by cryptonemo** [comment]
Based on slack discussion, I think I understand what's needed here, but I'm not clear on how best to proceed on this.  For testing, I suppose we could locally wrap the existing `LevelCacheStore` calls to use a callback that retrieves data from the store ... however, that only partially tests things since the base data layer is still present.

**Comment by dignifiedquire** [comment]
I would suggest for testing using a data layer that is easily generated e.g `node i = i + 3`,

**Comment by cryptonemo** [comment]
This was resolved some time ago via the `ExternalReader` interface.
